Upgrade to boost 1.55.
This fixes a compilation failure on gcc 4.8.2 on Fedora 20:

  In file included from /home/darren/packages/graphlab/deps/local/include/boost/atomic.hpp:12:0,
                   from /home/darren/packages/graphlab/deps/local/include/boost/lockfree/detail/atomic.hpp:39,
                   from /home/darren/packages/graphlab/deps/local/include/boost/lockfree/queue.hpp:22,
                   from /home/darren/packages/graphlab/src/graphlab/parallel/fiber_control.hpp:29,
                   from /home/darren/packages/graphlab/src/graphlab/parallel/fiber_group.hpp:26,
                   from /home/darren/packages/graphlab/src/graphlab/parallel/fiber_group.cpp:25:
  /home/darren/packages/graphlab/deps/local/include/boost/atomic/atomic.hpp:166:16: error: ‘uintptr_t’ was not declared in this scope
   typedef atomic<uintptr_t> atomic_uintptr_t;
                  ^
  /home/darren/packages/graphlab/deps/local/include/boost/atomic/atomic.hpp:166:25: error: template argument 1 is invalid
   typedef atomic<uintptr_t> atomic_uintptr_t;
                           ^
  /home/darren/packages/graphlab/deps/local/include/boost/atomic/atomic.hpp:166:43: error: invalid type in declaration before ‘;’ token
   typedef atomic<uintptr_t> atomic_uintptr_t;

The issue was known about and fixed in Boost 1.54 [1] but since Boost
1.55 is out already and seems to work, this commit upgrade graphlab to
use the later version.

[1] https://svn.boost.org/trac/boost/changeset/84950